name: practice_19072025
description: "A new Flutter project."
version: 1.0.0+1
environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.3
  vibration: ^3.1.3
  audioplayers: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/audios/
    - assets/gifs/
    - assets/icons/
    - assets/images/
    - assets/txt/
    - assets/videos/
